language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'

sudo: false

env:
    - DB_NAME=raster_test PYTHONPATH=$PYTHONPATH:$PWD DJANGO_SETTINGS_MODULE=settings USE_NOSE=True

before_script:
  - psql -c 'create database raster_test' -U postgres
  - psql -c 'create extension postgis' -U postgres -d raster_test

install:
  - pip install https://github.com/geodesign/django/archive/geodesign_v6.1.tar.gz
  - pip install psycopg2==2.5.3
  - pip install celery==3.1.19
  - pip install numpy
  - pip install Pillow==2.7.0
  - pip install django-colorful==1.0.1
  - pip install pyparsing==2.1.1
  - pip install flake8==2.5.0
  - pip install isort==4.2.2
  - pip install coverage==4.2
  - pip install coveralls

script: coverage run --include="raster/*" $(which django-admin.py) test

after_success: coveralls

notifications:
  email: false
